### ISSUE TITLE
Sass package no longer respects "word_separators" setting

### ISSUE THREAD

**Issue by mathijsprovoost** [SublimeText/Sass#105]
As of Sass v4.0.0 doubleclicking a CSS declaration in a scss file selects the whole word instead of the part in between the characters that are defined in the "word_separators" setting.

It's set to the default:
// Characters that are considered to separate words
"word_separators": "./\()"'-:,.;<>!@#$%^&*|+=[]{}`?",
[package.control.log](https://github.com/SublimeText/Sass/files/14663832/package.control.log)

**Comment by deathaxe** [comment]
Sass's word separators follow CSS word separator specifications (see https://www.w3.org/TR/selectors-3/#lex), as core CSS package has been doing since ST4130+ (https://github.com/sublimehq/Packages/pull/3287).

In detail it means `-` is normal part of an CSS identifier and thus was moved from `word_separators` to `sub_word_separators` via syntax specific settings.

see: https://github.com/SublimeText/Sass/blob/e390c842b09eb9d436cdfc18ad692733dbeb5450/Syntaxes/SCSS.sublime-settings#L10-L13

related core issues:

- https://github.com/sublimehq/sublime_text/issues/3908
- https://github.com/sublimehq/sublime_text/issues/5170

- https://github.com/sublimehq/Packages/issues/2709

It is working as expected.

**Comment by mathijsprovoost** [comment]
Specifying "sub_word_separators": "_-", in my settings doesn't resolve the issue.
I resolved the problem by uninstalling Sass v4 and manually installing  [v3.0.1](https://github.com/SublimeText/Sass/releases/tag/3.0.1)

**Comment by deathaxe** [comment]
Double-clicking select words, but not sub-words, thus selecting everything including `-` as those ar normal part of an identifier.

Listed settings above are the syntax specific defaults for CSS/Less/Sass/SCSS.

If you want the old behavior - instead of reverting to an older version with other bugs - a more suitable solution was to adjust syntax specific user settings.

1. Open a SCSS file
2. Open Command Palette
3. Call _Preferences: Settings - Syntax Specific_
4. On the right window, paste... (from Default/Default.sublime-settings)

   ```json
   "word_separators": "./\\()\"'-:,.;<>~!@#$%^&*|+=[]{}`~?",   
   "sub_word_separators": "_",
   ```

   ... to add `-` back to word separators.
