### ISSUE TITLE
No highlighting for Tailwind directives

### ISSUE THREAD

**Issue by mgussekloo** [SublimeText/Sass#112]
Hi,

There is no highlighting for Tailwind directives. I guess that is out of scope for this extension, but what would be the preferred way of handling this? Can a different extension "extend" this syntax highlighting, or could this extension maybe add support for popular libraries such as Tailwind?

I'll upload a screenshot to illustrate what I mean. Any help appreciated.

<img width="908" alt="Screenshot 2024-10-25 at 10 37 24" src="https://github.com/user-attachments/assets/da5921d7-be8f-4779-b192-bfd7814695a1">

**Comment by braver** [comment]
@mgussekloo Those directives work on the CSS level (if I read the [docs](https://tailwindcss.com/docs/functions-and-directives) correctly). In theory they could be added to the base [CSS package](https://github.com/sublimehq/Packages/tree/master/CSS) that Sass extends, but usually it's not a super great idea to do that for frameworks (especially front-end frameworks are typically a bit hard to keep track of on that level). So that's where a package like [Tailwind CSS](https://packagecontrol.io/packages/Tailwind%20CSS) comes in. I kind of don't think that inserts itself into the dependency chain in a way that it would make that syntax work inside SCSS as well. Since @deathaxe is that package's main contributor, and he's a major contributor to all related syntaxes in this space, I'm sure he has more to say on that matter.

**Comment by deathaxe** [comment]
I aggree with framwork specific tasks are risky to add to a core syntax due to mentioned reasons and the possibility of those conflicting.

If the question is for a standalone syntax definition the answer is...

Create a _Tailwind SCSS.sublime-syntax_ with following content:

```yml
%YAML 1.2
---
name: Tailwind SCSS
scope: source.scss.tailwind
version: 2

extends:
  - Tailwind CSS.sublime-syntax
  - Packages/Sass/Syntaxes/SCSS.sublime-syntax

file_extensions:
  - tailwind.scss
```

You wouldn't get highlighting in Vue Components or anything like that though as those embed basic SCSS syntax via `scope:source.scss`.

**Comment by deathaxe** [comment]
To also support highlighting in Svelte, Vue and other syntaxes, a possible solution is out-lined at https://github.com/SublimeText/TailwindCSS?tab=readme-ov-file#scss
