### ISSUE TITLE
No support for custom pseudo classes

### ISSUE THREAD

**Issue by niksy** [SublimeText/Sass#72]
Following code doesn’t add possibility to style custom pseudo class (upstream CSS syntax allows that).

```css
.example:enter {
	color: red;
}
```

**Comment by braver** [comment]
Fair point. This has a specific reason. It's part of the pattern matching that helps decide if what you're writing is a selector or a property. Because Sass can be nested (and CSS can't), this is needed to decide if `color:red` is a property or a selector with a pseudo class. I want to eventually revisit how this is handled. Sublime Text 4 brings a new way to write syntaxes with actual branching etc. It might be possible to keep the highlighting ambiguous longer (ie. while you're typing) and resolve the selector/property decision later. It's tricky though, because that also affects completions. But that would also make it possible to resolve interpolation in property-names (#54).
So, yeah, this is an issue, but it's a concession to make highlighting possible in unfinished blocks of codes.

**Comment by niksy** [comment]
Should we close this or wait for ST4 changes?

**Comment by braver** [comment]
Well I’ll probably remember even if we close this, but it’s still a valid issue. So let’s keep it open.
ST4 still feels like a moving target, so I want to wait for a little while still.

**Comment by braver** [comment]
A 3.0 beta release is out now, check [the readme](https://github.com/braver/SublimeSass#30-beta-release) on how to get the early builds to take advantage of the improvements and help out improving the package before we ship it to the world.

**Comment by braver** [comment]
closed via #96
